# Generated by Django 5.0.1 on 2024-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=255)),
                ('photo', models.IntegerField(null=True)),
                ('price', models.DateField(null=True)),
            ],
        ),
    ]
