# Generated by Django 5.0.1 on 2024-01-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_prodact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodact',
            new_name='Product',
        ),
    ]
