# Generated by Django 5.0.1 on 2024-01-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_prodact_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_publish',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
