# Generated by Django 5.0.1 on 2024-01-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_of_publish',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DateField(null=True),
        ),
    ]
