# Generated by Django 5.0.1 on 2024-01-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_product_date_of_publish_alter_product_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_data',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_1',
            field=models.IntegerField(null=True),
        ),
    ]
