# Generated by Django 5.0.1 on 2024-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_product_photo_data_product_price_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
